name = "1K granie auau"
author = "Przemek i pewnie jescze ktoś"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9556c8ec89d2d324aa8cf2f6c82608695cca2b471dd90df4b3c80e55ba6faca"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.17"
