name = "1K granie auau"
author = "Przemek i pewnie jescze ktoś"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e26c1f0b8a0d5b701bf67f5c4604929c7efdec3f975013c91d15c8731128e149"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.17"
